// Fumadocs source loader. Wraps the .source/ collection generated by
// `fumadocs-mdx` into a typed page tree mounted at /docs.

import { loader } from "fumadocs-core/source";
import { docs } from "../../.source/server";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
